apiVersion: apps/v1
kind: Deployment
metadata:
  name: eos-react-webapp
  labels:
    app: eos-react-webapp
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: eos-react-webapp
  template:
    metadata:
      labels:
        app: eos-react-webapp
    spec:
      containers:
      - name: eos-react-webapp
        image: {{ .Values.deployment.image }}
        ports:
        - containerPort: 3000
        readinessProbe:
          tcpSocket:
            port: 3000
        livenessProbe:
          tcpSocket:
            port: 3000
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
